# плохой compose для web (nginx) + redis

version: "3.9"

services:
  web:
    image: nginx:latest             
    container_name: web             
    user: root                      
    privileged: true                
    network_mode: host              
    ports:
      - "80:80"                     
    volumes:
      - ./:/usr/share/nginx/html    
    depends_on:
      - cache

  cache:
    image: redis:latest            
    container_name: redis
    environment:
      REDIS_PASSWORD: supersecret   
    command: ["redis-server","--appendonly","yes","--requirepass","supersecret"] 
    ports:
      - "6379:6379"                 
    volumes:
      - ./data:/data
    restart: always                