version: "3.9"

services:
  web:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"                            
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - web-net                               

  cache:
    image: redis:7.2-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    networks:
      - cache-net                             


volumes:
  redis-data:

networks:
  web-net:                                   
    driver: bridge
  cache-net:                                  
    driver: bridge
    internal: true                            