# Хороший docker-compose для web (nginx) + redis

version: "3.9"

services:
  web:
    image: nginx:1.25-alpine   # фиксированная версия
    ports:
      - "8080:80"             # публикуем только то, что реально нужно (http)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # монтируем только конфиг
      - ./html:/usr/share/nginx/html:ro         # монтируем только статику
    depends_on:
      - cache
    networks:
      - app-net

  cache:
    image: redis:7.2-alpine   # фиксированная версия
    command: ["redis-server","--appendonly","yes"]  # без пароля для учебы
    # пароль можно вынести в .env или secrets
    volumes:
      - redis-data:/data
    networks:
      - app-net

volumes:
  redis-data:

networks:
  app-net:
    driver: bridge